# Generated by Django 5.0.2 on 2024-02-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="student_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="teacher_id",
            field=models.IntegerField(),
        ),
    ]
