# Generated by Django 5.0.2 on 2024-02-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_studentprofile_student_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="student_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="teacher_id",
            field=models.IntegerField(default=1),
        ),
    ]
