# Generated by Django 5.0.2 on 2024-02-15 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_studentprofile_student_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="st_dob",
        ),
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Date of Birth"
            ),
        ),
    ]
