# Generated by Django 5.0.2 on 2024-02-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_studentprofile_st_dob_user_dob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacherprofile",
            name="t_dob",
        ),
    ]
