# Generated by Django 5.0.2 on 2024-02-15 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_teacherprofile_t_dob"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentMarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("English", models.IntegerField(default=0, max_length=100)),
                ("Hindi", models.IntegerField(default=0, max_length=100)),
                ("Marathi", models.IntegerField(default=0, max_length=100)),
                ("Maths", models.IntegerField(default=0, max_length=100)),
                ("Science", models.IntegerField(default=0, max_length=100)),
                (
                    "st_mk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
            ],
        ),
    ]
