# Generated by Django 5.0.2 on 2024-02-15 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_studentmarks_english_alter_studentmarks_hindi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmarks",
            name="st_mk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
