# Generated by Django 5.0.2 on 2024-02-15 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_studentmarks_st_mk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmarks",
            name="st_mk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.student"
            ),
        ),
    ]
