# Generated by Django 5.0.2 on 2024-02-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_studentprofile_student_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentcompetition",
            name="sport_image",
            field=models.ImageField(
                default="default.jpg", upload_to="competition_pictures"
            ),
        ),
    ]
