# Generated by Django 5.0.2 on 2024-02-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_studentcompetition_sport_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="student_image",
            field=models.ImageField(
                default="std_default.jpg", upload_to="student_pictures"
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="teacher_image",
            field=models.ImageField(
                default="teach_default.jpg", upload_to="teacher_pictures"
            ),
        ),
    ]
