# Generated by Django 5.0.2 on 2024-02-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_studentprofile_student_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_image",
            field=models.ImageField(
                default="admin_default.jpg", upload_to="admin_pictures"
            ),
        ),
    ]
