# Generated by Django 5.0.2 on 2024-02-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_admin_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcompetition",
            name="sport_desc",
            field=models.TextField(default="desc", max_length=200),
        ),
    ]
