# Generated by Django 5.0.2 on 2024-02-18 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_studentcompetition_sport_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_count", models.SmallIntegerField(default=1)),
                (
                    "order_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prod_id", models.SmallIntegerField(default=0, unique=True)),
                ("prod_name", models.CharField(max_length=30)),
                ("prod_desc", models.CharField(default="prod desc", max_length=500)),
                ("prod_price", models.SmallIntegerField(default=0)),
                (
                    "prod_img",
                    models.ImageField(
                        default="prod-default.jpg", upload_to="product_pictures"
                    ),
                ),
                (
                    "o",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.order"
                    ),
                ),
            ],
        ),
    ]
