# Generated by Django 5.0.2 on 2024-02-18 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_order_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="prod_ordered",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="o",
            field=models.ForeignKey(
                default="ADMIN",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
