# Generated by Django 5.0.2 on 2024-02-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_order_prod_ordered_alter_product_o"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="o",
            new_name="added_by",
        ),
    ]
