# Generated by Django 5.0.2 on 2024-02-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_rename_o_product_added_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
