# Generated by Django 5.0.2 on 2024-02-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_alter_order_order_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="prod_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
