# Generated by Django 5.0.2 on 2024-02-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_alter_product_prod_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
